# SWE546_Assignment2
Logistic Regression

Using the Iris dataset, find the optimum logistic regression parameters for the following three problems:

- Classify 1 versus 2,3
- Classify 2 versus 1,3
- Classify 3 versus 1,2


Your program should output three parameter vectors, each of length 4.
## Name: Okan Menevşeoğlu

In [1]:
# Necessary imports
import numpy as np
import pandas as pd

# Iris dataset
iris = pd.read_csv("data/iris.txt", sep=" ")

In [2]:
# Define logistic function
def logistic(t):
    return 1 / ( 1 + np.exp(-t))

In [3]:
# Define X matrix with the feature from the iris dataset
sepal_length = np.vstack(iris.sl)
sepal_width = np.vstack(iris.sw)
petal_length = np.vstack(iris.pl)
petal_width = np.vstack(iris.pw)
X = np.hstack((sepal_length, sepal_width, petal_length, petal_width))

In [4]:
# Define eta
eta = 0.001

In [5]:
# Define classification function
def classify(category):
    # Define y matrix
    y = np.vstack(iris.c)
    
    # Define w*
    w = np.matrix(np.ones(4)).T
    
    # Group by category (1 for the class that will be classified with, 0 for the others)
    for i in range(len(y)):
        y[i,0] = 1 if y[i,0] == category else 0
        
    # Iterate to find the optimal w
    for i in range(10000):
        prob = logistic(X * w)
        w = w + eta * X.T * (y - prob)
    return w

In [6]:
# Classify 1 versus 2,3
print(classify(1))

[[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]


In [7]:
# Classify 2 versus 1,3
print(classify(2))

[[ 0.73300616]
 [-1.87866542]
 [ 1.04693053]
 [-2.84352623]]


In [8]:
# Classify 3 versus 1,2
print(classify(3))

[[-4.80685745]
 [-4.96911165]
 [ 6.35877022]
 [ 7.88567013]]
